# Generated by Django 5.2.7 on 2025-11-13 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hospitals', to=settings.AUTH_USER_MODEL),
        ),
    ]
