# Generated by Django 5.2.7 on 2025-10-31 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_receiverprofile_options_adminprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='receiverprofile',
            name='full_name',
        ),
    ]
