# Generated by Django 5.2.7 on 2025-10-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_adminprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
