# Generated by Django 5.2.7 on 2025-10-23 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
                ('operating_hours', models.CharField(default='24/7', max_length=100)),
                ('storage_capacity', models.PositiveIntegerField(help_text='Maximum units that can be stored')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('managed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_blood_banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blood_banks',
            },
        ),
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('units_available', models.PositiveIntegerField(default=0)),
                ('units_reserved', models.PositiveIntegerField(default=0)),
                ('minimum_threshold', models.PositiveIntegerField(default=10, help_text='Alert when units fall below this number')),
                ('critical_threshold', models.PositiveIntegerField(default=5, help_text='Critical alert threshold')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='bloodbanks.bloodbank')),
            ],
            options={
                'db_table': 'blood_inventory',
                'indexes': [models.Index(fields=['blood_group', 'units_available'], name='blood_inven_blood_g_cb4a92_idx')],
                'unique_together': {('blood_bank', 'blood_group')},
            },
        ),
    ]
