# Generated by Django 5.2.7 on 2025-11-13 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbanks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='blood_bank_licenses/'),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_blood_banks', to=settings.AUTH_USER_MODEL),
        ),
    ]
