# Generated by Django 5.2.7 on 2025-10-31 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbanks', '0002_alter_bloodbank_managed_by'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_banks', to='locations.location'),
        ),
    ]
