# Generated by Django 5.2.7 on 2025-11-06 05:14

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloodbanks', '0001_initial'),
        ('bloodrequests', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('date_of_birth', models.DateField(default='2000-01-01')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg (minimum 45kg)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('45.00'))])),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('medical_conditions', models.TextField(blank=True, help_text='Any medical conditions that might affect donation')),
                ('is_available', models.BooleanField(default=True, help_text='Available for donation')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='donor_profiles/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('willing_to_travel_km', models.PositiveIntegerField(default=10, help_text='Maximum distance willing to travel (in km)')),
                ('preferred_donation_time', models.CharField(choices=[('MORNING', 'Morning (8AM-12PM)'), ('AFTERNOON', 'Afternoon (12PM-5PM)'), ('EVENING', 'Evening (5PM-8PM)'), ('ANYTIME', 'Anytime')], default='ANYTIME', max_length=20)),
                ('total_donations', models.PositiveIntegerField(default=0)),
                ('donation_points', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donors', to='locations.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_donors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donor_profiles',
            },
        ),
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('donation_date', models.DateTimeField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('units_donated', models.DecimalField(decimal_places=2, default=1.0, help_text='Units in pints', max_digits=4)),
                ('hemoglobin_level', models.DecimalField(blank=True, decimal_places=2, help_text='Hemoglobin level in g/dL', max_digits=4, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='SCHEDULED', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='bloodbanks.bloodbank')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_donations', to=settings.AUTH_USER_MODEL)),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='bloodrequests.bloodrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donors.donorprofile')),
            ],
            options={
                'db_table': 'donation_records',
                'ordering': ['-donation_date'],
            },
        ),
        migrations.AddIndex(
            model_name='donorprofile',
            index=models.Index(fields=['blood_group', 'is_available'], name='donor_profi_blood_g_7934ab_idx'),
        ),
        migrations.AddIndex(
            model_name='donorprofile',
            index=models.Index(fields=['location', 'blood_group'], name='donor_profi_locatio_25bc50_idx'),
        ),
        migrations.AddIndex(
            model_name='donationrecord',
            index=models.Index(fields=['donor', 'donation_date'], name='donation_re_donor_i_c1a79c_idx'),
        ),
        migrations.AddIndex(
            model_name='donationrecord',
            index=models.Index(fields=['status', 'donation_date'], name='donation_re_status_87dd61_idx'),
        ),
    ]
