# Generated by Django 5.2.7 on 2025-10-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='date_of_birth',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
