# Generated by Django 5.2.7 on 2025-11-15 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbanks', '0002_bloodbank_is_verified_bloodbank_license_document_and_more'),
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrecord',
            name='blood_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='bloodbanks.bloodbank'),
        ),
    ]
