# Generated by Django 5.2.7 on 2025-10-23 05:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloodbanks', '0001_initial'),
        ('bloodrequests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_donations', models.PositiveIntegerField(default=0)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('fulfilled_requests', models.PositiveIntegerField(default=0)),
                ('new_donors', models.PositiveIntegerField(default=0)),
                ('donations_by_group', models.JSONField(default=dict)),
                ('requests_by_group', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'donation_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RequestViewStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('top_requests', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blood Request View Statistic',
                'verbose_name_plural': 'Blood Request View Statistics',
                'db_table': 'request_view_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DistanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_to_donor_km', models.FloatField(blank=True, null=True)),
                ('receiver_to_hospital_km', models.FloatField(blank=True, null=True)),
                ('donor_to_hospital_km', models.FloatField(blank=True, null=True)),
                ('receiver_to_bloodbank_km', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blood_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodbanks.bloodbank')),
                ('blood_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodrequests.bloodrequest')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distance_as_donor', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distance_as_hospital', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distance_as_receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distance Record',
                'verbose_name_plural': 'Distance Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('DONOR_VERIFIED', 'Donor Verified'), ('REQUEST_CREATED', 'Request Created'), ('REQUEST_APPROVED', 'Request Approved'), ('DONATION_COMPLETED', 'Donation Completed'), ('INVENTORY_UPDATED', 'Inventory Updated'), ('CAMPAIGN_CREATED', 'Campaign Created')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='activity_lo_user_id_d23b30_idx'), models.Index(fields=['action', 'created_at'], name='activity_lo_action_0f3584_idx')],
            },
        ),
        migrations.CreateModel(
            name='BloodRequestView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='bloodrequests.bloodrequest')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blood Request View',
                'verbose_name_plural': 'Blood Request Views',
                'db_table': 'blood_request_views',
                'indexes': [models.Index(fields=['blood_request', 'viewed_at'], name='blood_reque_blood_r_6c15ec_idx'), models.Index(fields=['viewer'], name='blood_reque_viewer__8cbbd5_idx')],
                'unique_together': {('blood_request', 'session_key')},
            },
        ),
    ]
