# Generated by Django 5.2.7 on 2025-11-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_LOGIN_FAILED', 'User Login Failed'), ('DONOR_VERIFIED', 'Donor Verified'), ('REQUEST_CREATED', 'Request Created'), ('REQUEST_APPROVED', 'Request Approved'), ('DONATION_COMPLETED', 'Donation Completed'), ('INVENTORY_UPDATED', 'Inventory Updated'), ('CAMPAIGN_CREATED', 'Campaign Created')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
