# Generated by Django 5.2.7 on 2025-11-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_activitylog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_LOGIN_FAILED', 'User Login Failed'), ('USER_CREATED', 'User Created'), ('USER_CREATE_FAILED', 'User Create Failed'), ('DONOR_VERIFIED', 'Donor Verified'), ('REQUEST_CREATED', 'Request Created'), ('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_CANCELLED', 'Request Cancelled'), ('REQUEST_REJECTED', 'Request Rejected'), ('REQUEST_FULFILLED', 'Request Fulfilled'), ('DONATION_COMPLETED', 'Donation Completed'), ('INVENTORY_UPDATED', 'Inventory Updated'), ('CAMPAIGN_CREATED', 'Campaign Created')], max_length=50),
        ),
    ]
