# Generated by Django 5.2.7 on 2025-11-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_LOGIN_FAILED', 'User Login Failed'), ('USER_CREATED', 'User Created'), ('USER_CREATE_FAILED', 'User Create Failed'), ('DONOR_VERIFIED', 'Donor Verified'), ('DONOR_UNVERIFIED', 'Donor Unverified'), ('BLOOD_BANK_VERIFIED', 'Blood Bank Verified'), ('BLOOD_BANK_UNVERIFIED', 'Blood Bank Unverified'), ('HOSPITAL_VERIFIED', 'Hospital Verified'), ('HOSPITAL_UNVERIFIED', 'Hospital Unverified'), ('REQUEST_CREATED', 'Request Created'), ('REQUEST_UPDATED', 'Request Updated'), ('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_CANCELLED', 'Request Cancelled'), ('REQUEST_REJECTED', 'Request Rejected'), ('DONATION_COMPLETED', 'Donation Completed'), ('REQUEST_RESET', 'Request Reset'), ('INVENTORY_UPDATED', 'Inventory Updated'), ('CAMPAIGN_CREATED', 'Campaign Created')], max_length=50),
        ),
    ]
