# Generated by Django 5.2.7 on 2025-10-23 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloodbanks', '0001_initial'),
        ('donors', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDriveCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('venue_details', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('target_donors', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='campaign_banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_banks_involved', models.ManyToManyField(related_name='campaigns', to='bloodbanks.bloodbank')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blood_drive_campaigns',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('ATTENDED', 'Attended'), ('DONATED', 'Donated'), ('NO_SHOW', 'No Show'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_time_slot', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.blooddrivecampaign')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donorprofile')),
            ],
            options={
                'db_table': 'campaign_registrations',
                'unique_together': {('campaign', 'donor')},
            },
        ),
        migrations.AddField(
            model_name='blooddrivecampaign',
            name='registered_donors',
            field=models.ManyToManyField(related_name='campaigns', through='campaigns.CampaignRegistration', to='donors.donorprofile'),
        ),
    ]
